makesymlinks: Add check for GNU stow
This dotfile repo uses GNU stow to automate symlinking. Make sure that
utility exists to prevent errors about its absence

diff --git a/makesymlinks b/makesymlinks
--- a/makesymlinks
+++ b/makesymlinks
@@ -4,6 +4,19 @@
 # This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
 ############################
 
+# Check for GNU stow
+
+command -v stow
+stow_exists=$?
+
+if [ $stow_exists -eq 1 ]; then
+    echo "GNU stow not found in PATH. This script relies on that utility."
+    echo "Please install it."
+    exit 1
+fi
+
+# If we get here, we're good
+
 ########## Variables
 
 dir=~/dotfiles                    # dotfiles directory
